<a href="https://colab.research.google.com/github/kschoi93/AI/blob/master/pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 파이토치

In [1]:
import torch

In [2]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [3]:
x + y

tensor([[ 6.,  8.],
        [10., 12.]])

In [4]:
x - y

tensor([[-4., -4.],
        [-4., -4.]])

In [5]:
x * y 

tensor([[ 5., 12.],
        [21., 32.]])

In [6]:
x**2

tensor([[ 1.,  4.],
        [ 9., 16.]])

In [7]:
torch.mean(x+y)

tensor(9.)

In [8]:
x.mean()

tensor(2.5000)

In [9]:
x.mul(y)

tensor([[ 5., 12.],
        [21., 32.]])

In [14]:
torch.ones_like(x)

tensor([[1., 1.],
        [1., 1.]])

In [16]:
torch.zeros_like(y)

tensor([[0., 0.],
        [0., 0.]])

In [17]:
x.shape

torch.Size([2, 2])

In [18]:
x.view(-1,)

tensor([1., 2., 3., 4.])

In [27]:
x.view(-1).shape

torch.Size([4])

In [28]:
x.view(1,4)

tensor([[1., 2., 3., 4.]])

In [29]:
x.view(4,1)

tensor([[1.],
        [2.],
        [3.],
        [4.]])

In [38]:
squ = x.unsqueeze(0)
squ

tensor([[[1., 2.],
         [3., 4.]]])

In [40]:
squ.squeeze()

tensor([[1., 2.],
        [3., 4.]])

In [42]:
torch.stack([x,y])

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

In [46]:
torch.cat((y,x))

tensor([[5., 6.],
        [7., 8.],
        [1., 2.],
        [3., 4.]])