<a href="https://colab.research.google.com/github/kschoi93/AI/blob/master/%EC%8B%A4%EC%8A%B50_%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [5]:
a = torch.tensor([2.], requires_grad=True)
b = torch.tensor([1.], requires_grad=True)
c = a + b
d = b + 1
e = c * d
print(a)
print(b)
print(c)
print(d)
print(e)

tensor([2.], requires_grad=True)
tensor([1.], requires_grad=True)
tensor([3.], grad_fn=<AddBackward0>)
tensor([2.], grad_fn=<AddBackward0>)
tensor([6.], grad_fn=<MulBackward0>)


In [6]:
print(a.data)
print(a.grad)
print(a.grad_fn)

tensor([2.])
None
None


In [8]:
e.backward(retain_graph=True)

In [9]:
print(a.grad)
print(b.grad)
print(c.grad)
print(d.grad)
print(e.grad)

tensor([2.])
tensor([5.])
None
None
None


/usr/local/lib/python3.7/dist-packages/torch/_tensor.py:1104: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  aten/src/ATen/core/TensorBody.h:475.)
  return self._grad


In [10]:
a = torch.tensor([2.], requires_grad=True)
b = torch.tensor([1.], requires_grad=True)
c = a + b
d = b + 1
e = c * d

c.retain_grad()
d.retain_grad()
e.retain_grad()

In [21]:
e.backward(retain_graph=True)

In [22]:
print(a.data, a.grad)
print(b.grad)
print(c.grad)
print(d.grad)
print(e.grad)

tensor([2.]) tensor([10.])
tensor([25.])
tensor([10.])
tensor([15.])
tensor([5.])


In [24]:
a.grad.zero_()
b.grad.zero_()
c.grad.zero_()
d.grad.zero_()
e.grad.zero_()

print(a.data, a.grad)
print(b.grad)
print(c.grad)
print(d.grad)
print(e.grad)

tensor([2.]) tensor([0.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([0.])


In [25]:
a.requires_grad = False

In [26]:
print(a.grad)

tensor([0.])


In [27]:
a = a.detach()
print(a.requires_grad)

False


In [28]:
import torch.nn as nn
import torch.optim as optim

In [29]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(in_features=100, out_features=100, bias=True)
        self.fc1_act = nn.ReLU()
        self.fc2 = nn.Linear(in_features=100, out_features=10, bias=True)

    def forward(self, x):
        out = self.fc1(x)
        out = self.fc1_act(out)
        out = self.fc2(out)
        return out

In [30]:
net = Net()
print (net)

Net(
  (fc1): Linear(in_features=100, out_features=100, bias=True)
  (fc1_act): ReLU()
  (fc2): Linear(in_features=100, out_features=10, bias=True)
)


In [32]:
params = list(net.parameters())
print(len(params))
print(params[0].size())

4
torch.Size([100, 100])


In [33]:
for name, param in net.named_parameters():
    print(name)

fc1.weight
fc1.bias
fc2.weight
fc2.bias


In [36]:
print(net.fc1.weight)

Parameter containing:
tensor([[ 0.0929, -0.0740, -0.0735,  ..., -0.0187, -0.0741, -0.0078],
        [ 0.0355, -0.0234, -0.0260,  ...,  0.0383,  0.0077,  0.0402],
        [ 0.0750,  0.0223,  0.0746,  ..., -0.0683, -0.0580,  0.0438],
        ...,
        [ 0.0203, -0.0179,  0.0452,  ..., -0.0807, -0.0245, -0.0683],
        [-0.0513, -0.0679, -0.0789,  ...,  0.0683,  0.0138, -0.0184],
        [ 0.0968, -0.0855,  0.0351,  ...,  0.0550,  0.0032, -0.0962]],
       requires_grad=True)


In [37]:
batch_size = 10
input = torch.randn(batch_size, 100)
output = net(input)

target = torch.randn(batch_size, 10)
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)

tensor(0.8264, grad_fn=<MseLossBackward0>)


In [39]:
net.zero_grad()

print('conv1.bias.grad before backward')
print (net.fc1.bias.grad)

loss.backward()

print('fc1.bias.grad after backward')
print(net.fc1.bias.grad)

conv1.bias.grad before backward
None
fc1.bias.grad after backward
tensor([ 0.0083, -0.0067, -0.0002, -0.0165,  0.0054, -0.0054,  0.0045,  0.0021,
        -0.0046, -0.0109, -0.0117,  0.0051, -0.0017, -0.0058, -0.0085, -0.0017,
         0.0285, -0.0056,  0.0174, -0.0037, -0.0087,  0.0196,  0.0119, -0.0074,
         0.0170,  0.0165,  0.0009, -0.0107,  0.0007,  0.0049, -0.0015, -0.0042,
        -0.0066,  0.0080, -0.0035,  0.0076, -0.0039, -0.0048,  0.0008, -0.0085,
         0.0035, -0.0070, -0.0120,  0.0106,  0.0105, -0.0015,  0.0091,  0.0035,
        -0.0006, -0.0006,  0.0005,  0.0021,  0.0061,  0.0131, -0.0018,  0.0031,
         0.0006, -0.0008,  0.0039, -0.0050, -0.0019,  0.0020, -0.0043, -0.0035,
        -0.0086, -0.0130, -0.0065,  0.0011, -0.0042, -0.0034,  0.0097, -0.0018,
         0.0077,  0.0087,  0.0152,  0.0077, -0.0012, -0.0027, -0.0030, -0.0003,
        -0.0074,  0.0000,  0.0037,  0.0088,  0.0060,  0.0027, -0.0066,  0.0090,
         0.0120,  0.0211, -0.0032,  0.0026,  0.0092, -

In [40]:
learning_rate = 0.01
for param in net.parameters():
    param.data.sub_(param.grad.data * learning_rate)

In [41]:
optimizer = optim.SGD(net.parameters(), lr=learning_rate)

num_epochs = 100
for i in range(num_epochs):
    optimizer.zero_grad()
    output = net(input)
    loss = criterion(output, target)
    print(loss)
    loss.backward()
    optimizer.step()

tensor(0.8148, grad_fn=<MseLossBackward0>)
tensor(0.8035, grad_fn=<MseLossBackward0>)
tensor(0.7924, grad_fn=<MseLossBackward0>)
tensor(0.7815, grad_fn=<MseLossBackward0>)
tensor(0.7709, grad_fn=<MseLossBackward0>)
tensor(0.7606, grad_fn=<MseLossBackward0>)
tensor(0.7507, grad_fn=<MseLossBackward0>)
tensor(0.7409, grad_fn=<MseLossBackward0>)
tensor(0.7314, grad_fn=<MseLossBackward0>)
tensor(0.7222, grad_fn=<MseLossBackward0>)
tensor(0.7131, grad_fn=<MseLossBackward0>)
tensor(0.7041, grad_fn=<MseLossBackward0>)
tensor(0.6954, grad_fn=<MseLossBackward0>)
tensor(0.6868, grad_fn=<MseLossBackward0>)
tensor(0.6783, grad_fn=<MseLossBackward0>)
tensor(0.6700, grad_fn=<MseLossBackward0>)
tensor(0.6619, grad_fn=<MseLossBackward0>)
tensor(0.6539, grad_fn=<MseLossBackward0>)
tensor(0.6460, grad_fn=<MseLossBackward0>)
tensor(0.6383, grad_fn=<MseLossBackward0>)
tensor(0.6307, grad_fn=<MseLossBackward0>)
tensor(0.6231, grad_fn=<MseLossBackward0>)
tensor(0.6158, grad_fn=<MseLossBackward0>)
tensor(0.60